prisma:query SELECT `main`.`SiteContent`.`id`, `main`.`SiteContent`.`key`, `main`.`SiteContent`.`zh`, `main`.`SiteContent`.`en` FROM `main`.`SiteContent` WHERE 1=1 LIMIT ? OFFSET ?
prisma:query SELECT `main`.`NewsArticle`.`id`, `main`.`NewsArticle`.`date`, `main`.`NewsArticle`.`titleZh`, `main`.`NewsArticle`.`titleEn`, `main`.`NewsArticle`.`summaryZh`, `main`.`NewsArticle`.`summaryEn`, `main`.`NewsArticle`.`imageUrl`, `main`.`NewsArticle`.`order` FROM `main`.`NewsArticle` WHERE 1=1 ORDER BY `main`.`NewsArticle`.`order` ASC LIMIT ? OFFSET ?
-- SiteContent inserts
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('nav_home', '首页', 'Home');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('nav_about', '关于我们', 'About');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('nav_products', '产品中心', 'Products');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('nav_capabilities', '制造能力', 'Capabilities');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('nav_quality', '质量认证', 'Quality');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('nav_news', '新闻动态', 'News');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('nav_contact', '联系我们', 'Contact');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('nav_lang', 'EN', '中文');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('hero_title', '烟台富宁电子有限公司', 'Yantai Funing Electronics Co., Ltd.');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('hero_subtitle', '专业电子制造服务商', 'Professional Electronics Manufacturing Services');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('hero_description', '专注PCB制造、SMT贴片、电子组装及OEM/ODM服务，为全球客户提供高品质电子制造解决方案。', 'Specializing in PCB manufacturing, SMT assembly, electronics assembly, and OEM/ODM services, delivering high-quality electronics manufacturing solutions to global customers.');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('hero_cta', '了解更多', 'Learn More');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('hero_cta2', '联系我们', 'Contact Us');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('about_tag', '关于我们', 'About Us');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('about_title', '深耕电子制造，铸就卓越品质', 'Excellence in Electronics Manufacturing');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('about_p1', '烟台富宁电子有限公司成立于2008年，坐落于美丽的滨海城市——山东烟台。公司专注于印制电路板（PCB）制造、表面贴装技术（SMT）加工、电子组件组装及整机制造，是一家集研发、生产、销售于一体的综合性电子制造企业。', 'Founded in 2008, Yantai Funing Electronics Co., Ltd. is located in the beautiful coastal city of Yantai, Shandong Province. The company specializes in printed circuit board (PCB) manufacturing, surface mount technology (SMT) processing, electronic component assembly, and整机 manufacturing, serving as a comprehensive electronics manufacturing enterprise integrating R&D, production, and sales.');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('about_p2', '经过十余年的发展，富宁电子已建成现代化标准厂房超过20,000平方米，拥有多条全自动SMT产线、波峰焊产线及精密检测设备。公司年产能达到PCB 50万平方米、SMT贴片10亿点，产品广泛应用于消费电子、通信设备、工业控制、汽车电子、医疗器械等领域。', 'After more than a decade of development, Funing Electronics has built a modern standardized factory covering over 20,000 square meters, equipped with multiple fully automated SMT production lines, wave soldering lines, and precision inspection equipment. The company''s annual capacity reaches 500,000 square meters of PCB and 1 billion SMT placement points, with products widely used in consumer electronics, communication equipment, industrial control, automotive electronics, and medical devices.');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('about_p3', '我们始终秉持"质量为本、客户至上、持续创新"的经营理念，致力于成为全球电子制造领域值得信赖的合作伙伴。', 'We always adhere to the business philosophy of "Quality First, Customer Supreme, Continuous Innovation," committed to becoming a trusted partner in the global electronics manufacturing industry.');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('stat_years', '年行业经验', 'Years of Experience');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('stat_area', '平方米厂房面积', 'sqm Factory Area');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('stat_pcb', '万㎡年PCB产能', 'M sqm Annual PCB Capacity');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('stat_smt', '亿点年SMT产能', 'B Points Annual SMT Capacity');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('stat_clients', '+服务客户', '+Served Clients');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('stat_countries', '+出口国家', '+Export Countries');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('products_tag', '产品中心', 'Products');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('products_title', '一站式电子制造解决方案', 'One-Stop Electronics Manufacturing Solutions');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('products_subtitle', '从设计到交付，为您提供全流程电子制造服务', 'From design to delivery, providing full-process electronics manufacturing services');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('prod_pcb_title', 'PCB制造', 'PCB Manufacturing');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('prod_pcb_desc', '高精度多层印制电路板制造，支持1-32层板，涵盖FR-4、铝基板、高TG材料等多种基材，最小线宽线距3mil，满足高密度互连（HDI）需求。', 'High-precision multi-layer PCB manufacturing, supporting 1-32 layer boards with FR-4, aluminum base, high-TG materials, and more. Minimum trace width/space of 3mil, meeting HDI (High Density Interconnect) requirements.');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('prod_smt_title', 'SMT贴片', 'SMT Assembly');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('prod_smt_desc', '全自动高速SMT贴片加工，配备YAMAHA、松下等品牌贴片机，支持01005-50组件封装，BGA/CSP等高精度贴装，满足最小批量及大批量生产需求。', 'Fully automated high-speed SMT processing with YAMAHA and Panasonic placement machines. Supporting 01005-50 component packages, BGA/CSP high-precision mounting for both small batch and mass production.');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('prod_pca_title', 'PCBA组装', 'PCBA Assembly');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('prod_pca_desc', '提供PCB组装、波峰焊、选择性焊接等全流程组装服务。支持DIP插件、线束加工、整机组装及测试，具备完善的质量管控体系。', 'Full-process assembly services including PCB assembly, wave soldering, selective soldering. Supporting DIP insertion, cable harness processing, whole machine assembly and testing with a comprehensive quality control system.');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('prod_oem_title', 'OEM/ODM服务', 'OEM/ODM Services');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('prod_oem_desc', '提供从产品设计、原理图绘制、PCB Layout到批量生产的全流程OEM/ODM服务，拥有经验丰富的研发工程团队，可快速响应客户定制化需求。', 'End-to-end OEM/ODM services from product design, schematic drawing, PCB layout to mass production. An experienced R&D engineering team enables rapid response to customized customer needs.');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('prod_box_title', '整机制造', 'Box Build');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('prod_box_desc', '提供电子产品整机组装、外壳定制、包装设计等一站式服务。支持从小批量试产到大批量稳定交付，完善的供应链管理确保交期可控。', 'One-stop services for electronic product assembly, enclosure customization, and packaging design. Supporting small batch trial production to large-scale stable delivery with supply chain management ensuring on-time delivery.');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('prod_test_title', '测试服务', 'Testing Services');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('prod_test_desc', '配备AOI自动光学检测、X-Ray检测、ICT在线测试、FCT功能测试等先进检测设备，确保每一件产品都经过严格的质量验证。', 'Equipped with AOI automatic optical inspection, X-Ray inspection, ICT online testing, FCT functional testing and other advanced inspection equipment to ensure every product undergoes rigorous quality verification.');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('prod_view', '查看详情', 'View Details');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('cap_tag', '制造能力', 'Capabilities');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('cap_title', '先进设备与卓越产能', 'Advanced Equipment & Superior Capacity');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('cap_subtitle', '持续投入先进制造设备，打造行业领先的制造能力', 'Continuous investment in advanced manufacturing equipment to build industry-leading capabilities');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('cap_equip_title', '核心设备', 'Core Equipment');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('cap_equip_1', 'YAMAHA/松下高速贴片机', 'YAMAHA/Panasonic High-Speed Placement Machines');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('cap_equip_2', '十温区无铅回流焊', '10-Zone Lead-Free Reflow Oven');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('cap_equip_3', '选择性波峰焊设备', 'Selective Wave Soldering Equipment');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('cap_equip_4', 'AOI自动光学检测仪', 'AOI Automatic Optical Inspection');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('cap_equip_5', 'X-Ray检测设备', 'X-Ray Inspection Equipment');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('cap_equip_6', 'ICT/FCT在线测试系统', 'ICT/FCT Online Testing Systems');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('cap_equip_7', '高精度CNC钻孔机', 'High-Precision CNC Drilling Machines');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('cap_equip_8', '全自动电镀生产线', 'Automated Electroplating Production Lines');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('cap_line_title', '生产线配置', 'Production Lines');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('cap_line_1', '4条全自动高速SMT产线', '4 Fully Automated High-Speed SMT Lines');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('cap_line_2', '2条无铅波峰焊产线', '2 Lead-Free Wave Soldering Lines');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('cap_line_3', '1条选择性焊接产线', '1 Selective Soldering Line');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('cap_line_4', '3条整机组装测试线', '3 Box Build Assembly & Testing Lines');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('cap_line_5', '1条PCB精密制造线', '1 Precision PCB Manufacturing Line');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('cap_adv_title', '技术优势', 'Technical Advantages');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('cap_adv_1', '支持最小01005组件贴装', 'Support for 01005 Component Placement');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('cap_adv_2', '32层高多层PCB制造能力', '32-Layer High Multi-Layer PCB Capability');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('cap_adv_3', 'BGA间距0.3mm贴装精度', 'BGA 0.3mm Pitch Placement Precision');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('cap_adv_4', '无铅工艺RoHS compliant', 'Lead-Free Process, RoHS Compliant');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('cap_adv_5', '交期准时率99.5%以上', 'On-Time Delivery Rate Above 99.5%');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('quality_tag', '质量认证', 'Quality');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('quality_title', '以质量为核心竞争力', 'Quality as Our Core Competitiveness');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('quality_subtitle', '严格的质量管理体系，为每一件产品保驾护航', 'Rigorous quality management system protecting every product');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('q_iso', 'ISO 9001', 'ISO 9001');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('q_iso_desc', '国际质量管理体系认证，确保全过程质量管控', 'International Quality Management System certification ensuring full-process quality control');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('q_iso14001', 'ISO 14001', 'ISO 14001');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('q_iso14001_desc', '环境管理体系认证，践行绿色制造理念', 'Environmental Management System certification, practicing green manufacturing');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('q_iatf', 'IATF 16949', 'IATF 16949');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('q_iatf_desc', '汽车行业质量管理体系认证，满足汽车电子严苛要求', 'Automotive Industry Quality Management certification for stringent automotive electronics');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('q_ul', 'UL认证', 'UL Certification');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('q_ul_desc', '产品安全认证，确保产品符合国际安全标准', 'Product safety certification ensuring compliance with international safety standards');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('quality_p1', '富宁电子建立了完善的质量管理体系，从原材料进料检验（IQC）、生产过程控制（IPQC）、出货检验（OQC）到可靠性测试，实施全面质量控制。公司配备先进的检测设备和完善的质量追溯系统，确保产品全生命周期的质量可追溯。', 'Funing Electronics has established a comprehensive quality management system, implementing total quality control from incoming material inspection (IQC), in-process quality control (IPQC), outgoing quality control (OQC) to reliability testing. The company is equipped with advanced inspection equipment and a complete quality traceability system to ensure product quality traceability throughout the lifecycle.');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('quality_p2', '我们严格执行来料检验标准，对所有原材料进行100%检验或抽检；生产过程中实施SPC统计过程控制，关键工序配备CPK能力分析；出货前进行全面的AOI、X-Ray、ICT及功能测试，确保交付给客户的每一件产品都符合最高质量标准。', 'We strictly enforce incoming inspection standards, conducting 100% inspection or sampling of all raw materials. During production, SPC statistical process control is implemented with CPK capability analysis at critical processes. Before shipment, comprehensive AOI, X-Ray, ICT and functional testing is performed to ensure every product delivered meets the highest quality standards.');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('quality_process', '质量控制流程', 'Quality Control Process');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('quality_step1', 'IQC来料检验', 'IQC Incoming Inspection');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('quality_step2', 'SMT贴片管控', 'SMT Placement Control');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('quality_step3', '炉后AOI检测', 'Post-Reflow AOI Inspection');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('quality_step4', 'X-Ray透视检查', 'X-Ray Examination');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('quality_step5', 'ICT在线测试', 'ICT Online Testing');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('quality_step6', 'FCT功能测试', 'FCT Functional Testing');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('quality_step7', 'OQC出货检验', 'OQC Outgoing Inspection');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('news_tag', '新闻动态', 'News');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('news_title', '公司动态与行业资讯', 'Company Updates & Industry Insights');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('news_subtitle', '了解富宁电子的最新发展', 'Stay updated with Funing Electronics');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('news_read', '阅读全文', 'Read More');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('news_more', '查看更多', 'View All');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('news1_date', '2026-06-10', '2026-06-10');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('news1_title', '富宁电子荣获"2026年度山东省电子信息行业优秀企业"称号', 'Funing Electronics Awarded "2026 Shandong Electronic Information Industry Outstanding Enterprise"');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('news1_summary', '近日，山东省电子信息行业协会公布了2026年度行业评选结果，烟台富宁电子有限公司凭借卓越的制造能力和优质的服务水平，荣获"年度优秀企业"荣誉称号。', 'The Shandong Electronic Information Industry Association announced the 2026 industry selection results. Yantai Funing Electronics Co., Ltd. was honored with the "Outstanding Enterprise" title for its excellent manufacturing capabilities and high-quality service.');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('news2_date', '2026-05-20', '2026-05-20');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('news2_title', '公司第三条全自动SMT产线正式投产运行', 'Third Fully Automated SMT Production Line Officially Put into Operation');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('news2_summary', '为满足日益增长的市场需求，富宁电子投资建设的第三条全自动高速SMT产线已于5月正式投产运行，新增产能较原有产线提升40%，进一步巩固了公司在PCBA制造领域的竞争优势。', 'To meet growing market demand, Funing Electronics'' third fully automated high-speed SMT production line began operation in May. The new capacity increases production by 40% over existing lines, further strengthening the company''s competitive advantage in PCBA manufacturing.');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('news3_date', '2026-04-15', '2026-04-15');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('news3_title', '富宁电子通过IATF 16949汽车行业质量体系认证', 'Funing Electronics Achieves IATF 16949 Automotive Quality Certification');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('news3_summary', '经过近一年的体系建设与审核，富宁电子顺利通过IATF 16949:2016汽车行业质量管理体系认证，标志着公司在汽车电子制造领域迈入新阶段，为开拓汽车电子市场奠定了坚实的质量基础。', 'After nearly a year of system development and auditing, Funing Electronics successfully passed the IATF 16949:2016 automotive quality management system certification, marking a new stage in automotive electronics manufacturing.');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('contact_tag', '联系我们', 'Contact Us');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('contact_title', '期待与您的合作', 'Looking Forward to Cooperating with You');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('contact_subtitle', '无论您有任何电子制造需求，欢迎随时与我们联系', 'Whatever your electronics manufacturing needs, feel free to contact us');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('contact_address_label', '公司地址', 'Address');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('contact_address', '山东省烟台市经济技术开发区XX路XX号', 'XX Road, Economic & Technological Development Zone, Yantai, Shandong, China');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('contact_phone_label', '联系电话', 'Phone');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('contact_phone', '+86-535-XXXX-XXXX', '+86-535-XXXX-XXXX');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('contact_email_label', '电子邮箱', 'Email');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('contact_email', 'info@funing-electronics.com', 'info@funing-electronics.com');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('contact_hours_label', '工作时间', 'Business Hours');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('contact_hours', '周一至周五 8:00-17:30', 'Monday - Friday, 8:00 - 17:30');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('contact_form_name', '您的姓名', 'Your Name');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('contact_form_email', '电子邮箱', 'Email');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('contact_form_phone', '联系电话', 'Phone');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('contact_form_msg', '您的留言', 'Message');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('contact_form_submit', '提交留言', 'Submit');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('contact_form_success', '感谢您的留言！我们会尽快与您联系。', 'Thank you for your message! We will contact you soon.');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('footer_desc', '烟台富宁电子有限公司 — 您值得信赖的电子制造合作伙伴。专注PCB制造、SMT贴片、电子组装及OEM/ODM服务。', 'Yantai Funing Electronics Co., Ltd. — Your trusted electronics manufacturing partner. Specializing in PCB manufacturing, SMT assembly, electronics assembly and OEM/ODM services.');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('footer_links', '快速导航', 'Quick Links');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('footer_contact', '联系方式', 'Contact');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('footer_copyright', '© 2026 烟台富宁电子有限公司 版权所有', '© 2026 Yantai Funing Electronics Co., Ltd. All Rights Reserved.');
INSERT OR REPLACE INTO SiteContent (key, zh, en) VALUES ('footer_icp', '鲁ICP备XXXXXXXX号', 'Lu ICP No. XXXXXXXX');

-- NewsArticle inserts
INSERT INTO NewsArticle (date, titleZh, titleEn, summaryZh, summaryEn, imageUrl, "order") VALUES ('2026-06-10', '富宁电子荣获"2026年度山东省电子信息行业优秀企业"称号', 'Funing Electronics Awarded "2026 Shandong Electronic Information Industry Outstanding Enterprise"', '近日，山东省电子信息行业协会公布了2026年度行业评选结果，烟台富宁电子有限公司凭借卓越的制造能力和优质的服务水平，荣获"年度优秀企业"荣誉称号。', 'The Shandong Electronic Information Industry Association announced the 2026 industry selection results. Yantai Funing Electronics Co., Ltd. was honored with the "Outstanding Enterprise" title for its excellent manufacturing capabilities and high-quality service.', NULL, 1);
INSERT INTO NewsArticle (date, titleZh, titleEn, summaryZh, summaryEn, imageUrl, "order") VALUES ('2026-05-20', '公司第三条全自动SMT产线正式投产运行', 'Third Fully Automated SMT Production Line Officially Put into Operation', '为满足日益增长的市场需求，富宁电子投资建设的第三条全自动高速SMT产线已于5月正式投产运行，新增产能较原有产线提升40%。', 'To meet growing market demand, Funing Electronics'' third fully automated high-speed SMT production line began operation in May. The new capacity increases production by 40% over existing lines.', NULL, 2);
INSERT INTO NewsArticle (date, titleZh, titleEn, summaryZh, summaryEn, imageUrl, "order") VALUES ('2026-04-15', '富宁电子通过IATF 16949汽车行业质量体系认证', 'Funing Electronics Achieves IATF 16949 Automotive Quality Certification', '经过近一年的体系建设与审核，富宁电子顺利通过IATF 16949:2016汽车行业质量管理体系认证，标志着公司在汽车电子制造领域迈入新阶段。', 'After nearly a year of system development and auditing, Funing Electronics successfully passed the IATF 16949:2016 automotive quality management system certification.', NULL, 3);
